### ISSUE TITLE
01 오리엔테이션 및 replit 사용 2022/05/07 토 시간조율

### ISSUE THREAD

**Issue by umjiwan** [Team-Logic/OverView#1]
가능한 시간 적고가세요.
예상 소요 시간 1~1.5 시간

범진우 가능시간
오후 12시 ~ 오후 6시 사이 또는 오후 8시 ~ 11시 사이

**Comment by Cryingcats2** [comment]
오후 4시 이후

**Comment by seokwonmin-1124** [comment]
병원이 잡혀있어서 오후 12시 이후부터 가능

**Comment by umjiwan** [comment]
박병욱 - 오후 1~12시

**Comment by umjiwan** [comment]
이예준 오후 3시~ 9시

**Comment by umjiwan** [comment]
송호진 오후 5시 20분 이후

**Comment by umjiwan** [comment]
맞지 않는 시간이 범진우 임으로 
범진우가 밥을 늦게 먹도록 하여 
6시부터 7시 까지 활동을 하는것으로 하겠습니다.
