### ISSUE TITLE
2022년 5월 28일 로직 활동시간

### ISSUE THREAD

**Issue by umjiwan** [Team-Logic/OverView#2]
이번주 토요일(2022-05-28)
로직 동아리 활동 가능한시간 범위 각자 적어서 제출하세요
또는 개인 디코 메세지

제출하지 않고 불참시 강제 탈퇴

**Comment by umjiwan** [comment]
오후 2시 ~ 4시 or  오후 7시~ 10시

**Comment by seokwonmin-1124** [comment]
# 오후8시 ~ 오후10시

**Comment by kyleyjlee** [comment]
미투 오후8시 ~~

**Comment by umjiwan** [comment]
박병욱
특별한 일이 생기지 않으면 언제나 가능

**Comment by Cryingcats2** [comment]
오후 5시 이후

**Comment by umjiwan** [comment]
송호진 오후 8시 이후

**Comment by umjiwan** [comment]
5월 28일 로직 활동은 오후 8시~9시 30분 입니다
